#Color: HorizonDark

[colors]
#indexed_colors = [{ index = 0, color = ""},]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#e0e0e0"
background = "#1c1e26"
#dim_foreground = ""
#bright_foreground = ""
#cursor = { text = "CellBackground", cursor = "CellForeground" }
#vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
#matches = { foreground = "", background = "" }
#focused_match = {foreground = "", background = ""}

[colors.hints]
#start = { foreground = "", background = "" }
#end = { foreground = "", background = "" }
#line_indicator = { foreground = "", background = "" }
#footer_bar = { foreground = "", background = "" }
#selection = { foreground = "", background = "" }

[colors.normal]
black = "#16161c"
red = "#e95678"
green = "#29d398"
yellow = "#fab795"
blue = "#26bbd9"
magenta = "#ee64ac"
cyan = "#59e1e3"
white = "#d5d8da"

[colors.bright]
black = "#5b5858"
red = "#ec6a88"
green = "#3fdaa4"
yellow = "#fbc3a7"
blue = "#3fc4de"
magenta = "#f075b5"
cyan = "#6be4e6"
white = "#d5d8da"

[colors.dim] #if not set, auto calculated off of normal colors
#black = ""
#red = ""
#green = ""
#yellow = ""
#blue = ""
#magenta = ""
#cyan = ""
#white = ""

