#Color: Hyper

[colors]
#indexed_colors = [{ index = 0, color = ""},]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#ffffff"
background = "#000000"
#dim_foreground = ""
#bright_foreground = ""
#cursor = { text = "CellBackground", cursor = "CellForeground" }
#vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
#matches = { foreground = "", background = "" }
#focused_match = {foreground = "", background = ""}

[colors.hints]
#start = { foreground = "", background = "" }
#end = { foreground = "", background = "" }
#line_indicator = { foreground = "", background = "" }
#footer_bar = { foreground = "", background = "" }
#selection = { foreground = "", background = "" }

[colors.normal]
black = "#000000"
red = "#fe0100"
green = "#33ff00"
yellow = "#feff00"
blue = "#0066ff"
magenta = "#cc00ff"
cyan = "#00ffff"
white = "#d0d0d0"

[colors.bright]
black = "#808080"
red = "#fe0100"
green = "#33ff00"
yellow = "#feff00"
blue = "#0066ff"
magenta = "#cc00ff"
cyan = "#00ffff"
white = "#FFFFFF"

[colors.dim] #if not set, auto calculated off of normal colors
#black = ""
#red = ""
#green = ""
#yellow = ""
#blue = ""
#magenta = ""
#cyan = ""
#white = ""
